version: '3'

services:
  capybara.lol:
    build: .
    container_name: capybara.lol
    restart: always
    ports:
      - 4567:4567
    volumes:
      - capy-upload:/upload
      - capy-db:/db
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:////db/capybara.lol

volumes:
  capy-db:
  capy-upload: