version: '3'

services:
  capybara.lol:
    build: .
    container_name: capybara.lol
    restart: always
    ports:
      - 4567:4567
    volumes:
      - ./upload:/upload
      - ./db:/db
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:////db/capybara.lol